/**
 * Express-Führerschein
 * Upload/replace/delete the authenticated user's application signature.
 *
 * Supported methods:
 * - drawn: PNG generated by the signature canvas;
 * - uploaded: JPG, PNG or PDF selected by the client.
 */

import {
  NextResponse,
} from "next/server";

import {
  deleteCurrentApplicationSignature,
  uploadCurrentApplicationSignature,
} from "@/lib/server/driving-license-application/application-service";

import {
  DrivingLicenseApplicationServiceError,
} from "@/types/driving-license-application";

import type {
  DrivingLicenseApplicationSignatureType,
} from "@/types/driving-license-application";

export const dynamic =
  "force-dynamic";

export const runtime =
  "nodejs";

const SIGNATURE_TYPES =
  new Set<string>([
    "drawn",
    "uploaded",
  ]);

const ABSOLUTE_UPLOAD_LIMIT_BYTES =
  5 *
  1024 *
  1024;

function isSignatureType(
  value:
    unknown,
): value is
  DrivingLicenseApplicationSignatureType {
  return (
    typeof value ===
      "string" &&
    SIGNATURE_TYPES.has(
      value,
    )
  );
}

function statusForCode(
  code:
    DrivingLicenseApplicationServiceError["code"],
): number {
  switch (
    code
  ) {
    case "UNAUTHENTICATED":
      return 401;

    case "ACCOUNT_UNAVAILABLE":
      return 403;

    case "APPLICATION_NOT_FOUND":
      return 404;

    case "APPLICATION_NOT_EDITABLE":
      return 409;

    case "VALIDATION_ERROR":
    case "PROFILE_INCOMPLETE":
    case "DOCUMENT_REQUIRED":
    case "DOCUMENT_INVALID_TYPE":
    case "DOCUMENT_TOO_LARGE":
    case "SIGNATURE_REQUIRED":
    case "SIGNATURE_INVALID_TYPE":
    case "SIGNATURE_TOO_LARGE":
      return 422;

    case "STORAGE_NOT_CONFIGURED":
    case "STORAGE_ERROR":
    case "DATABASE_ERROR":
      return 503;

    case "EMAIL_DELIVERY_ERROR":
      return 502;

    default:
      return 500;
  }
}

function serviceErrorResponse(
  error:
    DrivingLicenseApplicationServiceError,
) {
  return NextResponse.json(
    {
      ok:
        false,

      code:
        error.code,

      message:
        error.message,
    },
    {
      status:
        statusForCode(
          error.code,
        ),
    },
  );
}

export async function POST(
  request:
    Request,
) {
  try {
    const formData =
      await request.formData();

    const signatureTypeValue =
      formData.get(
        "signatureType",
      );

    const fileValue =
      formData.get(
        "file",
      );

    if (
      !isSignatureType(
        signatureTypeValue,
      )
    ) {
      return NextResponse.json(
        {
          ok:
            false,

          code:
            "VALIDATION_ERROR",

          message:
            "Die Signaturmethode ist ungültig.",
        },
        {
          status:
            422,
        },
      );
    }

    if (
      !(fileValue instanceof File)
    ) {
      return NextResponse.json(
        {
          ok:
            false,

          code:
            "VALIDATION_ERROR",

          message:
            "Bitte füge eine Unterschrift hinzu.",
        },
        {
          status:
            422,
        },
      );
    }

    if (
      fileValue.size <=
        0 ||
      fileValue.size >
        ABSOLUTE_UPLOAD_LIMIT_BYTES
    ) {
      return NextResponse.json(
        {
          ok:
            false,

          code:
            "SIGNATURE_TOO_LARGE",

          message:
            fileValue.size <=
            0
              ? "Die Unterschrift ist leer oder ungültig."
              : "Die Unterschrift-Datei ist zu groß. Maximal 5 MB sind erlaubt.",
        },
        {
          status:
            422,
        },
      );
    }

    const bytes =
      new Uint8Array(
        await fileValue
          .arrayBuffer(),
      );

    const signature =
      await uploadCurrentApplicationSignature({
        signatureType:
          signatureTypeValue,

        bytes,

        mimeType:
          fileValue.type,

        originalFilename:
          fileValue.name,
      });

    return NextResponse.json(
      {
        ok:
          true,

        message:
          "Die Unterschrift wurde sicher gespeichert.",

        data:
          signature,
      },
      {
        status:
          200,
      },
    );
  } catch (
    error:
      unknown
  ) {
    if (
      error instanceof
      DrivingLicenseApplicationServiceError
    ) {
      return serviceErrorResponse(
        error,
      );
    }

    console.error(
      "[DRIVING_LICENSE_APPLICATION_SIGNATURE_UPLOAD_ROUTE_ERROR]",
      error instanceof Error
        ? error.message
        : error,
    );

    return NextResponse.json(
      {
        ok:
          false,

        code:
          "INTERNAL_ERROR",

        message:
          "Die Unterschrift konnte gerade nicht gespeichert werden.",
      },
      {
        status:
          500,
      },
    );
  }
}

export async function DELETE() {
  try {
    await deleteCurrentApplicationSignature();

    return NextResponse.json(
      {
        ok:
          true,

        message:
          "Die Unterschrift wurde entfernt.",
      },
      {
        status:
          200,
      },
    );
  } catch (
    error:
      unknown
  ) {
    if (
      error instanceof
      DrivingLicenseApplicationServiceError
    ) {
      return serviceErrorResponse(
        error,
      );
    }

    console.error(
      "[DRIVING_LICENSE_APPLICATION_SIGNATURE_DELETE_ROUTE_ERROR]",
      error instanceof Error
        ? error.message
        : error,
    );

    return NextResponse.json(
      {
        ok:
          false,

        code:
          "INTERNAL_ERROR",

        message:
          "Die Unterschrift konnte gerade nicht entfernt werden.",
      },
      {
        status:
          500,
      },
    );
  }
}
