-- ============================================================================
-- Express-Führerschein
-- 001_registration.sql
--
-- PostgreSQL migration for:
-- - user accounts
-- - e-mail verification codes
-- - shared registration rate limits
--
-- UUID values are generated by the application layer.
-- This avoids requiring a PostgreSQL UUID extension.
-- ============================================================================

BEGIN;

-- ============================================================================
-- USERS
-- ============================================================================

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,

    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,

    email VARCHAR(254) NOT NULL,
    phone_e164 VARCHAR(16) NOT NULL,

    country_code CHAR(2) NOT NULL,

    password_hash TEXT NOT NULL,

    accepted_terms_at TIMESTAMPTZ NOT NULL,

    email_verified_at TIMESTAMPTZ NULL,

    status VARCHAR(32) NOT NULL DEFAULT 'pending_verification',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_users_first_name
        CHECK (char_length(trim(first_name)) BETWEEN 2 AND 80),

    CONSTRAINT chk_users_last_name
        CHECK (char_length(trim(last_name)) BETWEEN 2 AND 80),

    CONSTRAINT chk_users_email
        CHECK (
            char_length(trim(email)) BETWEEN 3 AND 254
            AND position('@' IN email) > 1
        ),

    CONSTRAINT chk_users_phone_e164
        CHECK (phone_e164 ~ '^\+[1-9][0-9]{6,14}$'),

    CONSTRAINT chk_users_country
        CHECK (country_code IN ('DE', 'AT', 'CH', 'BE', 'ES')),

    CONSTRAINT chk_users_status
        CHECK (
            status IN (
                'pending_verification',
                'active',
                'disabled'
            )
        )
);

-- E-mail is normalized to lowercase by the application layer.
-- The functional unique index also protects against case variants.

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_normalized
    ON users ((lower(email)));

CREATE INDEX IF NOT EXISTS idx_users_status
    ON users (status);

CREATE INDEX IF NOT EXISTS idx_users_country_code
    ON users (country_code);

CREATE INDEX IF NOT EXISTS idx_users_created_at
    ON users (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_users_phone_e164
    ON users (phone_e164);


-- ============================================================================
-- EMAIL VERIFICATIONS
-- ============================================================================

CREATE TABLE IF NOT EXISTS email_verifications (
    id UUID PRIMARY KEY,

    user_id UUID NOT NULL,

    email VARCHAR(254) NOT NULL,

    -- HMAC-SHA256 hex digest.
    -- Never store the six-digit verification code in plaintext.
    code_hash CHAR(64) NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,

    attempts SMALLINT NOT NULL DEFAULT 0,
    resend_count SMALLINT NOT NULL DEFAULT 0,

    last_sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    used_at TIMESTAMPTZ NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_email_verifications_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_email_verifications_attempts
        CHECK (attempts >= 0 AND attempts <= 100),

    CONSTRAINT chk_email_verifications_resend_count
        CHECK (resend_count >= 0 AND resend_count <= 100),

    CONSTRAINT chk_email_verifications_code_hash
        CHECK (code_hash ~ '^[0-9a-fA-F]{64}$'),

    CONSTRAINT chk_email_verifications_expiration
        CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS idx_email_verifications_user
    ON email_verifications (user_id);

CREATE INDEX IF NOT EXISTS idx_email_verifications_email
    ON email_verifications ((lower(email)));

CREATE INDEX IF NOT EXISTS idx_email_verifications_expires_at
    ON email_verifications (expires_at);

CREATE INDEX IF NOT EXISTS idx_email_verifications_created_at
    ON email_verifications (created_at DESC);

-- Only one currently unused verification row per user.
-- Resending a code updates the existing active row.

CREATE UNIQUE INDEX IF NOT EXISTS uq_email_verifications_active_user
    ON email_verifications (user_id)
    WHERE used_at IS NULL;


-- ============================================================================
-- SHARED REGISTRATION RATE LIMITS
-- ============================================================================
--
-- The current development implementation can run in memory.
-- This table is available for production when the application runs across
-- multiple processes/instances and therefore needs a shared rate-limit store.
-- ============================================================================

CREATE TABLE IF NOT EXISTS registration_rate_limits (
    id BIGSERIAL PRIMARY KEY,

    identifier_hash CHAR(64) NOT NULL,

    scope VARCHAR(32) NOT NULL,

    request_count INTEGER NOT NULL DEFAULT 0,

    window_started_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_registration_rate_limits_scope
        CHECK (
            scope IN (
                'start',
                'verify',
                'resend'
            )
        ),

    CONSTRAINT chk_registration_rate_limits_count
        CHECK (request_count >= 0),

    CONSTRAINT chk_registration_rate_limits_identifier
        CHECK (identifier_hash ~ '^[0-9a-fA-F]{64}$'),

    CONSTRAINT chk_registration_rate_limits_expiration
        CHECK (expires_at > window_started_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_registration_rate_limit_window
    ON registration_rate_limits (
        identifier_hash,
        scope,
        window_started_at
    );

CREATE INDEX IF NOT EXISTS idx_registration_rate_limits_expires_at
    ON registration_rate_limits (expires_at);


-- ============================================================================
-- AUTOMATIC updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION ef_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_users_updated_at
ON users;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE FUNCTION ef_set_updated_at();


DROP TRIGGER IF EXISTS trg_email_verifications_updated_at
ON email_verifications;

CREATE TRIGGER trg_email_verifications_updated_at
BEFORE UPDATE ON email_verifications
FOR EACH ROW
EXECUTE FUNCTION ef_set_updated_at();


DROP TRIGGER IF EXISTS trg_registration_rate_limits_updated_at
ON registration_rate_limits;

CREATE TRIGGER trg_registration_rate_limits_updated_at
BEFORE UPDATE ON registration_rate_limits
FOR EACH ROW
EXECUTE FUNCTION ef_set_updated_at();


COMMIT;
