-- ============================================================================
-- Express-Führerschein
-- 002_auth_login.sql
--
-- PostgreSQL migration for:
-- - unique telephone login;
-- - authenticated user sessions;
-- - Google / Apple OAuth account links.
--
-- Depends on:
-- - 001_registration.sql
-- - users table
-- - ef_set_updated_at() trigger function
--
-- UUID values are generated by the application layer.
-- Raw browser session tokens are NEVER stored in the database.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1. USERS — UNIQUE TELEPHONE LOGIN
-- ============================================================================
--
-- 001_registration.sql already creates:
--
--   users.phone_e164
--
-- and a normal lookup index:
--
--   idx_users_phone_e164
--
-- Login by telephone requires a single telephone number to identify at most
-- one Express-Führerschein account.
--
-- This migration therefore replaces the non-unique index with a unique index.
-- If duplicate phone numbers already exist, this migration intentionally fails
-- so the duplicate data can be corrected instead of silently weakening login.
-- ============================================================================

DROP INDEX IF EXISTS idx_users_phone_e164;

CREATE UNIQUE INDEX IF NOT EXISTS uq_users_phone_e164
    ON users (phone_e164);


-- ============================================================================
-- 2. AUTH SESSIONS
-- ============================================================================
--
-- Browser:
--   ef_session=<opaque random token>
--
-- Database:
--   SHA-256(token) only
--
-- The raw session token must never be stored server-side.
-- ============================================================================

CREATE TABLE IF NOT EXISTS auth_sessions (
    id UUID PRIMARY KEY,

    user_id UUID NOT NULL,

    token_hash CHAR(64) NOT NULL,

    expires_at TIMESTAMPTZ NOT NULL,

    revoked_at TIMESTAMPTZ NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_auth_sessions_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_auth_sessions_token_hash
        CHECK (token_hash ~ '^[0-9a-fA-F]{64}$'),

    CONSTRAINT chk_auth_sessions_expiration
        CHECK (expires_at > created_at),

    CONSTRAINT chk_auth_sessions_revocation
        CHECK (
            revoked_at IS NULL
            OR revoked_at >= created_at
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_sessions_token_hash
    ON auth_sessions (token_hash);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id
    ON auth_sessions (user_id);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at
    ON auth_sessions (expires_at);

CREATE INDEX IF NOT EXISTS idx_auth_sessions_active_user
    ON auth_sessions (user_id, expires_at DESC)
    WHERE revoked_at IS NULL;


-- ============================================================================
-- 3. OAUTH ACCOUNT LINKS
-- ============================================================================
--
-- One provider identity can belong to only one local user:
--
--   UNIQUE(provider, provider_account_id)
--
-- One local user can have at most one account per provider:
--
--   UNIQUE(user_id, provider)
--
-- Provider access/refresh tokens are intentionally not stored here.
-- ============================================================================

CREATE TABLE IF NOT EXISTS oauth_accounts (
    id UUID PRIMARY KEY,

    user_id UUID NOT NULL,

    provider VARCHAR(16) NOT NULL,

    provider_account_id VARCHAR(255) NOT NULL,

    email VARCHAR(254) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_oauth_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT chk_oauth_accounts_provider
        CHECK (
            provider IN (
                'google',
                'apple'
            )
        ),

    CONSTRAINT chk_oauth_accounts_provider_account_id
        CHECK (
            char_length(trim(provider_account_id))
            BETWEEN 1 AND 255
        ),

    CONSTRAINT chk_oauth_accounts_email
        CHECK (
            char_length(trim(email))
            BETWEEN 3 AND 254
            AND position('@' IN email) > 1
        )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_oauth_accounts_provider_identity
    ON oauth_accounts (
        provider,
        provider_account_id
    );

CREATE UNIQUE INDEX IF NOT EXISTS uq_oauth_accounts_user_provider
    ON oauth_accounts (
        user_id,
        provider
    );

CREATE INDEX IF NOT EXISTS idx_oauth_accounts_user_id
    ON oauth_accounts (user_id);

CREATE INDEX IF NOT EXISTS idx_oauth_accounts_email_normalized
    ON oauth_accounts ((lower(email)));


-- ============================================================================
-- 4. AUTOMATIC updated_at
-- ============================================================================
--
-- ef_set_updated_at() is created by 001_registration.sql.
-- ============================================================================

DROP TRIGGER IF EXISTS trg_auth_sessions_updated_at
ON auth_sessions;

CREATE TRIGGER trg_auth_sessions_updated_at
BEFORE UPDATE ON auth_sessions
FOR EACH ROW
EXECUTE FUNCTION ef_set_updated_at();


DROP TRIGGER IF EXISTS trg_oauth_accounts_updated_at
ON oauth_accounts;

CREATE TRIGGER trg_oauth_accounts_updated_at
BEFORE UPDATE ON oauth_accounts
FOR EACH ROW
EXECUTE FUNCTION ef_set_updated_at();


-- ============================================================================
-- 5. OPTIONAL MAINTENANCE NOTES
-- ============================================================================
--
-- Expired sessions can be periodically cleaned with:
--
--   DELETE FROM auth_sessions
--   WHERE expires_at <= NOW();
--
-- Revoked sessions may also be retained temporarily for audit purposes and
-- deleted later according to the project's retention policy.
-- ============================================================================

COMMIT;
